# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Anjuan Simmons
jobtitle: "Technology Translator"
email: 
description: > # this means to ignore newlines until "baseurl:"
  I'm a Technology Translator. Welcome to my site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.AnjuanSimmons.com/" # the base hostname & protocol for your site
twitter_username: anjuan
github_username:  anjuan

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: anjuansimmons

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
excerpt_separator: "<!--more-->"

# Google Analytics
google_analytics: UA-112266652-1

# SEO stuff
google_author: "https://plus.google.com/u/0/+AnjuanSimmons"

plugins:
  - jekyll-sitemap
  - html-proofer


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
